apiVersion: v1
kind: Service
metadata:
  name: collab
  namespace: researchflow
  labels:
    app.kubernetes.io/name: researchflow
    app.kubernetes.io/component: collab
spec:
  type: ClusterIP
  ports:
    - port: 1234
      targetPort: 1234
      name: http
    - port: 1235
      targetPort: 1235
      name: health
  selector:
    app.kubernetes.io/name: researchflow
    app.kubernetes.io/component: collab
