apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: researchflow

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - orchestrator-deployment.yaml
  - worker-deployment.yaml
  - web-deployment.yaml
  - ingress.yaml
  - pruning-cronjob.yaml

commonLabels:
  app.kubernetes.io/part-of: researchflow
  app.kubernetes.io/managed-by: kustomize

images:
  - name: researchflow/orchestrator
    newTag: latest
  - name: researchflow/worker
    newTag: latest
  - name: researchflow/web
    newTag: latest
